# Generated by Django 3.0.2 on 2020-02-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_accomodation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='car_booking',
            field=models.NullBooleanField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='flight_booking',
            field=models.NullBooleanField(default=0, max_length=10),
        ),
    ]
