# Generated by Django 3.0.2 on 2020-02-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200207_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='urlhash',
            field=models.CharField(default='SRF0PX', max_length=6),
        ),
    ]
