# Generated by Django 3.0.2 on 2020-02-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200207_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='accomodation',
            name='people',
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='urlhash',
            field=models.CharField(default='RZ8Q3N', max_length=6),
        ),
    ]
