# Generated by Django 3.0.2 on 2020-02-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200207_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='status',
            field=models.NullBooleanField(default=1, max_length=5, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='urlhash',
            field=models.CharField(max_length=6),
        ),
    ]
