# Generated by Django 3.0.2 on 2020-02-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200207_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='car_booking',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='flight_booking',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
