# Generated by Django 3.0.2 on 2020-02-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Category'),
        ),
    ]
