# Generated by Django 3.0.2 on 2020-02-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_hotel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
