# Generated by Django 3.0.2 on 2020-02-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200211_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.CharField(default='Hotel', max_length=255),
        ),
    ]
