# Generated by Django 3.0.2 on 2020-02-11 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200211_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Hotel', verbose_name='Belongs to'),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number available'),
        ),
    ]
