# Generated by Django 3.0.2 on 2020-02-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200211_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='car_booking',
        ),
        migrations.RemoveField(
            model_name='accomodation',
            name='flight_booking',
        ),
    ]
