# Generated by Django 3.0.2 on 2020-02-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200218_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='room_type',
            field=models.CharField(default='Economy Class', max_length=255),
        ),
    ]
