# Generated by Django 3.0.2 on 2020-03-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200225_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='category',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='category',
            field=models.CharField(default='Hotel', max_length=255),
        ),
    ]
