# Generated by Django 3.0.2 on 2020-03-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user_id',
        ),
    ]
