# Generated by Django 3.0.2 on 2020-03-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_transaction_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='amenities',
            field=models.CharField(default='WI-Fi', max_length=255),
        ),
    ]
