# Generated by Django 3.0.2 on 2020-03-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_accomodation_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
