# Generated by Django 3.0.2 on 2020-01-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200115_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
    ]
