# Generated by Django 3.0.2 on 2020-02-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('urlhash', models.CharField(blank=True, max_length=6, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('inquiry', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
