# Generated by Django 3.0.2 on 2020-02-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200207_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='inclusives',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
