# Generated by Django 3.0.2 on 2020-03-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking_inclusives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='inclusives',
        ),
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
