# Generated by Django 3.0.2 on 2020-03-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200302_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
