# Generated by Django 3.0.2 on 2020-03-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200302_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
