# Generated by Django 3.0.2 on 2020-03-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200303_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mpesa_receipt_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.NullBooleanField(default=0, max_length=5, verbose_name='Payment status'),
        ),
    ]
